# Generated by Django 2.2.5 on 2019-09-26 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prayer_type', models.CharField(choices=[('praise', 'Praise'), ('request', 'Request')], max_length=100)),
                ('prayer_contents', models.TextField()),
                ('prayer_privacy', models.CharField(choices=[('public', 'Available to Public'), ('protected', 'Available to Registered User'), ('prayer_team', 'Available to Prayer Team'), ('staff', 'Available to Church Staff')], max_length=100)),
                ('status', models.CharField(choices=[('automatic_approval', 'Automatically Approved (Verified Account)'), ('approved', 'Approved After Review'), ('awaiting_approval', 'Waiting For Approval')], max_length=100)),
                ('allow_support', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Account')),
            ],
            options={
                'verbose_name': 'Prayer',
                'verbose_name_plural': 'Prayers',
            },
        ),
        migrations.CreateModel(
            name='PrayerSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_type', models.CharField(choices=[('praying', 'Praying for your request!'), ('praising', 'Praising along side you!')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prayers.Prayer')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Account')),
            ],
            options={
                'verbose_name': 'Prayer Support Action',
                'verbose_name_plural': 'Prayer Support Actions',
            },
        ),
    ]
